export const HEAVY_BRANDS = [
  'Chevrolet',
  'Hino',
  'International',
  'Foton',
  'JAC',
  'Isuzu',
  'Kenworth',
  'Freightliner',
  'Volvo',
  'Scania',
  'Mercedes-Benz',
  'Volkswagen',
  'Ford',
  'Iveco',
  'Nissan',
  'Hyundai',
  'Mitsubishi Fuso',
  'Renault Trucks',
  'Sinotruk',
  'Shacman',
  'Dongfeng',
  'UD Trucks',
  'MAN',
  'DAF',
  'Mack',
  'Camc',
  'Howo',
  'Agrale',
  'Toyota',
  'Mazda',
  'Kia',
  'Otro',
];

export const COMMON_COLORS = [
  'Blanco',
  'Gris',
  'Plata',
  'Negro',
  'Azul',
  'Rojo',
  'Verde',
  'Amarillo',
  'Naranja',
  'Beige',
];

export const MODELS_BY_BRAND: Record<string, string[]> = {
  Chevrolet: ['NHR', 'NKR', 'NPR', 'NQR', 'FRR', 'FTR', 'FVR', 'LV150', 'LV260'],
  Hino: ['300', '500', '700', 'FC', 'FG', 'GH', 'XZU'],
  International: ['4300', '4400', '7600', 'WorkStar', 'DuraStar', 'ProStar'],
  Foton: ['Aumark', 'Ollin', 'BJ', 'Auman'],
  JAC: ['N55', 'N75', 'N90', 'N120', 'N200', 'K7'],
  Isuzu: ['NHR', 'NKR', 'NPR', 'NQR', 'FTR', 'FVR', 'CYZ'],
  Kenworth: ['T300', 'T370', 'T800', 'T880', 'C500'],
  Freightliner: ['M2 106', 'M2 112', 'Columbia', 'Cascadia', '114SD'],
  Volvo: ['VM', 'VNL', 'FM', 'FH'],
  Scania: ['P250', 'P360', 'G410', 'R450'],
  'Mercedes-Benz': ['Accelo', 'Atego', 'Actros', 'Axor'],
  Volkswagen: ['Delivery', 'Constellation', 'Worker'],
  Ford: ['Cargo', 'F-350', 'F-550'],
  Iveco: ['Daily', 'Tector', 'Hi-Way'],
  Nissan: ['Cabstar', 'UD'],
  Hyundai: ['HD65', 'HD78', 'HD120'],
  'Mitsubishi Fuso': ['Canter', 'Fighter', 'FV'],
  'Renault Trucks': ['D', 'C', 'K'],
  Sinotruk: ['Howo', 'T5G', 'TX'],
  Shacman: ['X3000', 'F3000'],
  Dongfeng: ['Captain', 'Kinland'],
  'UD Trucks': ['Croner', 'Quester'],
  MAN: ['TGS', 'TGX'],
  DAF: ['CF', 'XF'],
  Mack: ['Granite', 'Anthem'],
  Camc: ['H08', 'H9'],
  Howo: ['A7', 'TX', '371'],
  Agrale: ['A8700', 'A10000'],
  Toyota: ['Hilux', 'Land Cruiser'],
  Mazda: ['BT-50'],
  Kia: ['K2700', 'K3000'],
};

export const getSuggestedYears = () => {
  const currentYear = new Date().getFullYear();
  return Array.from({ length: 10 }, (_, index) => `${currentYear - index}`);
};
